// UI behaviour constants

export const APP = {
  NAME: 'StreamHub',
  PAGE_SIZE: 12,
  COMMENT_PAGE_SIZE: 20,
  SEARCH_DEBOUNCE_MS: 400,
  TOAST_DURATION_MS: 3000,
  MAX_COMMENT_LENGTH: 1000,
  MAX_TWEET_LENGTH: 280,
  SIDEBAR_WIDTH: 240,
  SIDEBAR_MINI_WIDTH: 72,
}